server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # Laravel public folder
    root /var/www/html/public;
    index index.php index.html;

    server_name _;

    # THIS is the key line Laravel needs
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Pass PHP scripts to FastCGI server
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 300;
    }

    # Deny access to .htaccess 
    location ~ /\.ht {
        deny all;
    }
}
